---
# tasks file for chromeos-secrets
- name: Install secret management packages
  ansible.builtin.package:
    name: "{{ chromeos_keyring_packages | join(',') }}"
- name: Create systemd unit for secrets services
  ansible.builtin.template:
    src: gnome-keyring-daemon.service.j2
    dest: /etc/systemd/user/gnome-keyring-daemon.service
    owner: root
    group: root
    mode: 0644
- name: Create systemd unit for secrets socker
  ansible.builtin.template:
    src: gnome-keyring-daemon.socket.j2
    dest: /etc/systemd/user/gnome-keyring-daemon.socket
    owner: root
    group: root
    mode: 0644
- name: Enable keyring service
  ansible.builtin.systemd:
    name: gnome-keyring-daemon.service
    state: started
    enabled: true
    daemon_reload: true
    scope: user
  become: false
- name: Enable keyring environmental varialble
  ansible.builtin.template:
    src: gnome-keyring.sh.j2
    dest: /etc/profile.d/gnome-keyring.sh
    owner: root
    group: root
    mode: 0644
